#spring:
#  application:
#    name: Ecommerce
#  web:
#    resources:
#      cache:
#        period: 60m
#  liquibase:
#    enabled: false
#  datasource:
#    url: jdbc:h2:mem:testdb1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    h2:
#      console:
#        enabled: true
#  jpa:
#    open-in-view: false

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080
  servlet:
    context-path: /ecommerce