databaseChangeLog:
  - changeSet:
      id: v1.0-product
      author: HimaBindu
      changes:
        - createTable:
            tableName: PRODUCT
            columns:
              - column:
                  name: ID
                  type: int
                  #autoIncrement: true
                  defaultValueSequenceNext: SEQ_PRODUCT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: PRODUCT_NAME
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: PRODUCT_TYPE
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: CREATED_BY
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: CREATED_AT
                  type: datetime
                  defaultValueDate: ${now}
              #                  constraints:
              #                    nullable: false
              - column:
                  name: UPDATED_BY
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: UPDATED_AT
                  type: datetime
                  defaultValueDate: ${now}
  #                  constraints:
  #                    nullable: false

#  - changeSet:
#      id: v1.0-product-seed-data
#      file: db/data/v1.0/product_seed_data.csv
#      author: HimaBindu
#      changes:
#        - loadData:
#            encoding: UTF-8
#            separator: ';'
#            tableName: PRODUCT
#            columns:
#              - column:
#                  name: PRODUCT_NAME
#                  type: STRING
#              - column:
#                  name: PRODUCT_TYPE
#                  type: STRING
#              - column:
#                  name: CREATED_BY
#                  type: STRING
#              - column:
#                  name: UPDATED_BY
#                  type: STRING
